[package]
name = "imp-language"
version = "0.1.0"
authors = ["Jamie Brandon <jamie@scattered-thoughts.net>"]
edition = "2018"
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.3"
regex = "0.2.0"

# Add a build-time dependency on the lalrpop library:
[build-dependencies]
lalrpop = "0.16.3"