authors = ["Jamie Brandon <jamie@scattered-thoughts.net>"]
name = "Imp"
uuid = "b410ecec-65a3-11e8-3f20-07a7b460a33b"
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Rematch = "bfecab0d-fd4d-5014-a23f-56c5fae6447a"
