[package]
name = "imp_tests"
version = "0.1.0"
authors = ["Jamie Brandon <jamie@scattered-thoughts.net>"]
edition = "2018"

[dependencies]
imp_language = {path = "../imp_language"}
walkdir = "2"
log = "*"
env_logger = "*"